---
# tasks file for ansible-role-docker

# Nuke existing docker packages
- name: Remove existing docker packages
  package:
    name:
      - docker
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-latest
      - docker-latest-logrotate
      - docker-logrotate
      - docker-engine
    state: absent

- name: install yum-utils
  package:
    name: yum-utils
    state: present

- name: Add repository
  yum_repository:
    name: epel
    description: Docker Repo
    baseurl: https://download.docker.com/linux/centos/7/x86_64/stable/
    gpgcheck: no

- name: install docker packages
  package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present

- name: Creates service directory
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory

- name: Creates service directory
  file:
    path: /etc/docker/
    state: directory

- name: Create service file
  template:
    src: options.conf.j2
    dest: /etc/systemd/system/docker.service.d/options.conf
    owner: root
    group: root
    mode: 0600
  notify:
    - restart docker

- name: restart docker
  systemd:
    name: docker
    state: reloaded
    daemon_reload: yes
    enabled: yes

- name: restart docker
  systemd:
    name: docker
    state: restarted
    daemon_reload: yes
    enabled: yes

- name: Enable swarm
  include: "swarm.yml"
  when:
    - docker_swarm

- name: update the system
  yum:
    name: "*"
    state: latest

- name: restart system to reboot to newest kernel
  shell: "sleep 5 && reboot"
  async: 1
  poll: 0

- name: wait for 10 seconds
  pause:
    seconds: 10

- name: wait for the system to reboot
  wait_for_connection:
    connect_timeout: 20
    sleep: 5
    delay: 5
    timeout: 60

- name: install epel-release
  yum:
    name: epel-release
    state: latest
