---
# tasks file for ansible-role-docker

# Nuke existing docker packages
- name: Remove existing docker packages
  package:
    name:
      - docker
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-latest
      - docker-latest-logrotate
      - docker-logrotate
      - docker-engine
    state: absent

- name: install yum-utils
  package:
    name: yum-utils
    state: present

- name: Add repository
  yum_repository:
    name: epel
    description: Docker Repo
    baseurl: https://download.docker.com/linux/centos/7/x86_64/stable/
    gpgcheck: no

- name: install docker packages
  package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present

- name: Creates service directory
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory

- name: Creates service directory
  file:
    path: /etc/docker/
    state: directory

- name: Create service file
  template:
    src: options.conf.j2
    dest: /etc/systemd/system/docker.service.d/options.conf
    owner: root
    group: root
    mode: 0600
  notify:
    - restart docker

- name: restart docker
  systemd:
    name: docker
    state: reloaded
    daemon_reload: yes
    enabled: yes

- name: Check if Swarm has already been Initialized
  shell: docker node ls
  register: swarm_status
  ignore_errors: true
  when:
    - docker_master

- name: Initialize Docker Swarm
  shell: >
        docker swarm init
        --advertise-addr={{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:2377
  when:
    - swarm_status.rc != 0
    - docker_master
  run_once: true

- name: Get the worker join-token
  shell: docker swarm join-token --quiet worker
  register: worker_token
  when: docker_master

- name: Add Workers to the Swarm
  shell: "docker swarm join --token {{ hostvars['docker.me.imhadmin.net']['worker_token']['stdout'] }} {{ hostvars['docker.me.imhadmin.net']['ansible_default_ipv4']['address'] }}:2377"
  when: not docker_master

#- name: Add local registry config
#  template:
#    src: daemon.json.j2
#    dest: /etc/docker/daemon.json
#    owner: root
#    group: root
#    mode: 0600
#  notify:
#    - restart docker
